# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
$os\
$directory\

$localip\
$python\
$rust\
$zig\
$c\
$cpp\
$docker_context\
$golang\
$lua\
$php\
$nodejs\
$java\
$dotnet\
$ruby\

$git_branch\

$fill\

$cmd_duration\
$time\n\


$hostname\
$username\
$character\
"""

# $package\
# $git_commit\
# $git_state\
# $fossil_branch\
# $nix_shell\
# $container\
# $git_metrics\
# $git_status\
# $shlvl\
# $shell\
# $env_var\
# $jobs\
# $sudo\
# $singularity\
# $kubernetes\
# $vcsh\
# $hg_branch\
# $pijul_channel\
# $cmake\
# $cobol\
# $daml\
# $dart\
# $deno\
# $elixir\
# $elm\
# $erlang\
# $fennel\
# $fortran\
# $guix_shell\
# $haskell\
# $haxe\
# $helm\
# $julia\
# $kotlin\
# $gradle\
# $nim\
# $ocaml\
# $opa\
# $perl\
# $pulumi\
# $purescript\
# $raku\
# $rlang\
# $red\
# $scala\
# $solidity\
# $swift\
# $terraform\
# $vlang\
# $vagrant\
# $xmake\
# $buf\
# $conda\
# $pixi\
# $meson\
# $spack\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $crystal\
# $custom\
# $status\
# $battery

[fill]
symbol = ' '

[character]
format = "$symbol "

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'
disabled = true

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
disabled = true

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
read_only = " 󰌾"
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) (bold bright-blue)'

[cmd_duration]
format = "[$duration ](italic dimmed white)"
min_time = 0
show_milliseconds = true

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"
disabled = true

[localip]
ssh_only = true
format = " 󰢹[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[fossil_branch]
symbol = " "
disabled = true

[git_branch]
symbol = " "
format = " [$symbol$branch(:$remote_branch)]($style)"
style = "italic bright-blue"
truncation_symbol = "⋯"
truncation_length = 11
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = true

[git_status]
style = "bold italic bright-blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪◦](italic bright-magenta)"
ahead = "[▴│[${count}](bold white)│](italic green)"
behind = "[▿│[${count}](bold white)│](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◃◈](italic white)"
modified = "[●◦](italic yellow)"
staged = "[▪┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"
disabled = true

[git_commit]
tag_symbol = '  '

[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"
symbol = " "

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = " "
style = "bold bright-yellow"

[nodejs]
format = " [node](italic) [◫ ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []
symbol = " "

[python]
format = " [py](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
style = "bold bright-yellow"
symbol = " "

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = " "
version_format = "${raw}"
style = "bold red"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = "󱘗 "
version_format = "${raw}"
style = "bold red"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "󰏗 "
style = "dimmed yellow italic bold"

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = " "
style = "bold bright-red"
version_format = "${raw}"

[aws]
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"
symbol = " "

[buf]
symbol = " "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[cpp]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[cmake]
symbol = " "

[conda]
symbol = " "
format = " conda [$symbol$environment]($style)"

[crystal]
symbol = " "

[pixi]
symbol = "󰏗 "
format = " pixi [$symbol$version ($environment )]($style)"

[dart]
symbol = " "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"

[elixir]
symbol = " "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = " "
format = " elm [$symbol($version )]($style)"

[golang]
symbol = " "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = " "
format = " hs [$symbol($version )]($style)"

[java]
symbol = " "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = " "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "
format = " mem [${ram}( ${swap})]($style)"

[nim]
symbol = "󰆥 "
format = " nim [$symbol($version )]($style)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = " "
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed yellow)'


[bun]
symbol = " "

[fortran]
symbol = " "

[fennel]
symbol = " "

[gcloud]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[kotlin]
symbol = " "

[meson]
symbol = "󰔷 "

[ocaml]
symbol = " "

[os]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[scala]
symbol = " "

[status]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
